name = "AdaptiveMCMC"
uuid = "7599756a-d2e4-11e9-0d0e-31645f1f853c"
authors = ["Arthur ZWAENEPOEL <arzwa@psb.ugent.be>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
